export const types = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',

    CREATE_ROUTIN: 'CREATE_ROUTIN',
    UPDATE_ROUTIN: 'UPDATE_ROUTIN',
    DELETE_ROUTIN: 'DELETE_ROUTIN',
    COMPLETED_ROUTIN: 'COMPLETED_ROUTIN',
};
