import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';
import Providers from '../reactQuery/Providers';

const myFont = localFont({ src: '../public/fonts/Pretendard-Medium.woff2' });
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${myFont.className} flex justify-center items-center h-screen`}>
                <Providers>{children} </Providers>
            </body>
        </html>
    );
}
